#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PathSim Simulation
==================

Generated by PathView on 2026-02-22 00:44:55
https://view.pathsim.org

PathSim documentation: https://docs.pathsim.org
"""

# ────────────────────────────────────────────────────────────────────────────
# IMPORTS
# ────────────────────────────────────────────────────────────────────────────

import numpy as np
import matplotlib.pyplot as plt

from pathsim import Simulation, Connection, BusConnection
from pathsim.blocks import (
    BusCreator,
    BusSelector,
    Constant,
    Scope
)
from pathsim.solvers import SSPRK22

# ────────────────────────────────────────────────────────────────────────────
# USER-DEFINED CODE
# ────────────────────────────────────────────────────────────────────────────

bus = ['a', 'b']

# ────────────────────────────────────────────────────────────────────────────
# BLOCKS
# ────────────────────────────────────────────────────────────────────────────

# Sources
b = Constant(
    value=10
)
a = Constant()

# Algebraic
buscreator = BusCreator(
    keys=bus
)
busselector = BusSelector(
    keys=['a', 'b']
)

# Recording
scope = Scope()

blocks = [
    b,
    a,
    buscreator,
    busselector,
    scope,
]

# ────────────────────────────────────────────────────────────────────────────
# CONNECTIONS
# ────────────────────────────────────────────────────────────────────────────

connections = [
    Connection(a[0], buscreator[0]),
    Connection(b[0], buscreator[1]),
    BusConnection(buscreator[0], busselector[0]),
    Connection(busselector[0], scope[0]),
    Connection(busselector[1], scope[1]),
]

# ────────────────────────────────────────────────────────────────────────────
# SIMULATION
# ────────────────────────────────────────────────────────────────────────────

sim = Simulation(
    blocks,
    connections,
    Solver=SSPRK22,
    dt=0.01,
    dt_min=1e-16,
    tolerance_lte_rel=0.0001,
    tolerance_lte_abs=1e-08,
    tolerance_fpi=1e-10,
)

# ────────────────────────────────────────────────────────────────────────────
# MAIN
# ────────────────────────────────────────────────────────────────────────────

if __name__ == '__main__':

    # Run simulation
    sim.run(duration=10.0)

    # Plot results
    sim.plot()
    plt.show()
